
// Copyright Tempo Simulation, LLC. All Rights Reserved

/* This file was generated by a TempoROS prebuild step and should not be modified. */

#pragma once

#include "TempoROSCommonConverters.h"

#include "TempoROSNode.h"

#include "Kismet/BlueprintFunctionLibrary.h"

#include "TempoROSTempoROSBlueprintFunctionLibrary.generated.h"

DECLARE_DYNAMIC_DELEGATE_OneParam(FTempoROSFStringReceived, FString, Value);

UCLASS(BlueprintType)
class TEMPOROS_API UTempoROSTempoROSBlueprintFunctionLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

    UFUNCTION(BlueprintCallable)
    static bool Publish(UTempoROSNode* Node, const FString& Topic, const FString& Message)
    {
        return Node->Publish<FString>(Topic, Message);
    }

    UFUNCTION(BlueprintCallable)
    static bool AddSubscription(UTempoROSNode* Node, const FString& Topic, const FTempoROSFStringReceived& TempoROSMessageReceivedEvent)
    {
        return Node->AddSubscription<FString>(Topic, TROSSubscriptionDelegate<FString>::CreateLambda([TempoROSMessageReceivedEvent](const FString& Value)
        {
            TempoROSMessageReceivedEvent.ExecuteIfBound(Value);
        }));
    }
};
